app:
  name: "dev_web_app_v1.0"
  mode: ""
  port: 8080

log:
  level: "debug"
  filename: "./web_app.log"
  max_size: 200
  max_backups: 7
  max_age: 30
  Compress: false

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: ""
  dbname: ""

redis:
  host: "127.0.0.1"
  password: ""
  port: 6379
  db: 0

email:
  host: "smtp.qq.com"
  port: 465
  email_pass:
    - username: ""
      password: ""
    - username: ""
      password: ""
  expires: 500

secret: "hackerxiao"

jwt:
  timeout: 168 #小时
  issuer: "hackerxiao"
  secret: "sylu"

snowflake:
  start_time: "2023-06-16"
  machine_id: 1

proxy:
  type: "socks5"
  host: "127.0.0.1"
  port: "8899"

cos:
  tmpsecret:
    id: ""
    key: ""
  resource:
    allowpath: ""
    region: "ap-beijing"
    appid: ""
    bucket: ""
    allow_key:
      - "/testAvatar/*.jpg"
      - "/testAvatar/*.png"
  action:
    - "name/cos:PostObject"
    - "name/cos:PutObject"
    - "name/cos:GetObject"
